In [13]:
!pip install pandas

Collecting pandas
  Downloading pandas-3.0.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Requirement already satisfied: numpy>=1.26.0 in /opt/conda/lib/python3.12/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 57.2 MB/s  0:00:00
Installing collected packages: pandas
Successfully installed pandas-3.0.2

In [1]:
# data collection throught APIs
import requests

In [15]:
url = "https://stephen-king-api.onrender.com/api/books"

res = requests.get(url)

json_data = res.json()

In [17]:
import pandas as pd

df = pd.json_normalize(json_data['data'])

In [18]:
df = df[['id', 'Title', 'Year', 'ISBN']]

In [19]:
df

    id          Title  Year               ISBN
0    1         Carrie  1974  978-0-385-08695-0
1    2    Salem's Lot  1975  978-0-385-00751-1
2    3    The Shining  1977  978-0-385-12167-5
3    4           Rage  1977  978-0-451-07645-8
4    5      The Stand  1978  978-0-385-12168-2
..  ..            ...   ...                ...
58  59   The Outsider  2018  978-1-50118-098-9
59  60      Elevation  2018  978-1-98210-231-9
60  61  The Institute  2019  978-1-98211-056-7
61  62          Later  2021  978-1-78909-649-1
62  63  Billy Summers  2021  978-1-982-17361-6

[63 rows x 4 columns]

In [24]:
res = requests.get("https://dogapi.dog/api/v2/breeds")
json_data = res.json()

In [32]:
df = pd.json_normalize(json_data['data'])

In [34]:
df = df[['type', 'attributes.name','attributes.description']]
df

,type,attributes.name,attributes.description
0,breed,Affenpinscher,The Affenpinscher is a small and playful breed...
1,breed,Afghan Hound,The Afghan Hound is a large and elegant breed ...
2,breed,Airedale Terrier,The Airedale Terrier is a large and powerful b...
3,breed,Akita,"The Akita is a large, muscular dog breed that ..."
4,breed,Alaskan Klee Kai,The Alaskan Klee Kai is a small to medium-size...
...,...,...,...
278,breed,Wirehaired Vizsla,The Wirehaired Vizsla is a medium-sized breed ...
279,breed,Working Kelpie,The Working Kelpie is a medium-sized breed of ...
280,breed,Xoloitzcuintli,"The Xoloitzcuintli, also known as the Mexican ..."
281,breed,Yakutian Laika,The Yakutian Laika is a medium-sized breed of ...
282,breed,Yorkshire Terrier,"The Yorkshire Terrier is a small, intelligent ..."